# Generated by Django 2.2 on 2021-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('empleados', models.ManyToManyField(related_name='Actividades', to='empleados.Empleados')),
            ],
        ),
    ]
